<span style='color:blue'>Importamos las clases y funciones

In [1]:
from modules3 import *

<span style='color:blue'>Creamos un juego

In [2]:
obs = game_obs()
obs.place_pieces()
obs.compute_legal_moves()
obs.display_board()

<span style='color:blue'>Creamos un agente para jugar las piezas azules

In [3]:
agente1 = agent('b', info=True)

<span style='color:blue'>Es el agente más básico posible: escoge una pieza al azar (de entre las que pueden moverse) y realiza un movimiento al azar (de entre los legales)

In [4]:
agente1.play(obs)

Se selecciona al azar la pieza de (7, 6)
El caballo de (7, 6) se ha movido a (5, 7)

In [5]:
obs.display_board()

<span style='color:blue'>Si volvemos a intentar jugar con el mismo agente se nos imprime un mensaje advirtiéndonos de que esto no es posible porque no es su turno

In [6]:
agente1.play(obs)

No puedes jugar ahora, no es tu turno

<span style='color:blue'>Reseteamos el juego y creamos dos agentes (uno de cada color) que juegen una partida con 2 movimientos cada uno

In [7]:
movements_each = 2

obs = game_obs()
obs.place_pieces()
obs.compute_legal_moves()

agente1 = agent('b', info=True)
agente2 = agent('r', info=True)

for i in range(2*movements_each):
    if i%2 == 0: agente1.play(obs)
    else: agente2.play(obs)
obs.display_board()

Se selecciona al azar la pieza de (6, 6)
El peón de (6, 6) se ha movido a (5, 6)
Se selecciona al azar la pieza de (1, 5)
El peón de (1, 5) se ha movido a (3, 5)
Se selecciona al azar la pieza de (6, 0)
El peón de (6, 0) se ha movido a (4, 0)
Se selecciona al azar la pieza de (1, 2)
El peón de (1, 2) se ha movido a (2, 2)

<span style='color:blue'>Probamos un nuevo agente que elige (si puede) una pieza aleatoria entre las que pueden capturar y realiza uno de los movimientos que acaba en captura. Generamos una situación en la que la dama azul de (3, 7) puede capturar cualquiera de los tres peones situados en: (3, 4), (2,6), (1,7)

In [8]:
obs = game_obs()
obs.place_pieces()
obs.compute_legal_moves()

obs.move_piece((6, 4), (4, 4))
obs.move_piece((1, 4), (3, 4))
obs.move_piece((7, 3), (3, 7))
obs.move_piece((1, 6), (2, 6))
obs.display_board()

agente = agent('b', stgy_selection='pro1', stgy_move='pro1', info=True)
agente.play(obs)
obs.display_board()

Se selecciona a conciencia la pieza de (3, 7)
La dama de (3, 7) ha capturado el peón de (2, 6)

<span style='color:blue'>Sin embargo, jugar partidas hasta que uno de los dos agentes consiga el jaque mate aún no funciona bien...

In [9]:
# obs = game_obs()
# obs.place_pieces()
# obs.compute_legal_moves()

# agente1 = agent('b', info=True)
# agente2 = agent('r', info=True)

# contador = 0
# while obs.check_mate != 1:
#     if contador%2 == 0: agente1.play(obs)
#     else: agente2.play(obs)
#     obs.display_board()
#     contador += 1
#     print(contador)